
pg: &pg
  adapter: postgresql
  encoding: unicode

development:
  <<: *pg
  database: encom-pg_development

test:
  <<: *pg
  database: encom-pg_test

production:
  <<: *pg
  database: encom-pg_production

secondbase:

  mysql: &mysql
    adapter: mysql
    encoding: utf8
    username: root
    password:
    host: localhost

  development:
    <<: *mysql
    database: encom-mysql_development

  test:
    <<: *mysql
    database: encom-mysql_test

  production:
    <<: *mysql
    database: encom-mysql_production

