
development:
  adapter: postgresql
  encoding: unicode
  database: encom_dbs_32_development
  pool: 5
  username: encom_dbs_32
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: encom_dbs_32_test
  pool: 5
  username: encom_dbs_32
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: encom_dbs_32_production
  pool: 5
  username: encom_dbs_32
  password:
