
development:
  adapter: postgresql
  encoding: unicode
  database: encom_dbs_32_development
  pool: 5
  username: encom_dbs_32
  password:
  prepared_statements: false

test:
  adapter: postgresql
  encoding: unicode
  database: encom_dbs_32_test
  pool: 5
  username: encom_dbs_32
  password:
  prepared_statements: false

production:
  adapter: postgresql
  encoding: unicode
  database: encom_dbs_32_production
  pool: 5
  username: encom_dbs_32
  password:
  prepared_statements: false

mysql:

  development:
    adapter: mysql
    encoding: utf8
    reconnect: false
    database: encom_dbs_32_development
    pool: 5
    username: root
    password:
    host: localhost
    prepared_statements: false

  test:
    adapter: mysql
    encoding: utf8
    reconnect: false
    database: encom_dbs_32_test
    pool: 5
    username: root
    password:
    host: localhost
    prepared_statements: false

  production:
    adapter: mysql
    encoding: utf8
    reconnect: false
    database: encom_dbs_32_production
    pool: 5
    username: root
    password:
    host: localhost
    prepared_statements: false
