development:
  secret_key_base: fd4650fef5dc6d1658c672ce6924fb8a33a0d6e2a8dd

test:
  secret_key_base: d3c8da1e1f69bd67e2ca587a7afe65a2b27d93110c3b

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
